import Head from 'next/head'
import Image from 'next/image'
import Bodi from '../components/Bodi'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className="min-h-screen min-w-screen bg-green-50 dark:bg-black dark:text-gray-200">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
     
       <Bodi/>
     

      <footer >
    
      </footer>
    </div>
  )
}
